# **LED Lifetime Prediction V2**

## **0.Import Data**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dataset=[]

import os
for root,dirs,files in os.walk("/content/"):
  for file in files:
       if file.endswith(".csv"):
          print(file)
          try:
            new=pd.read_csv(file,header=None,index_col=False,names=['wavelenght','A','B','C','D','E'])
            print(new)
            #split file name
            file=file[:-4].split("_")
            #drop restart
            if file[-1]=='restart':
              file=file[0:-1]
            #get mA
            mA=int(file[3][:-2])
            #get hr
            if 'o' in file[4][:-2]:
              spl=file[4][:-2].split("o")
              hr=int(spl[0])+int(spl[1])/10
            else:
              hr=int(file[4][:-2])
            #get tem
            tem=int(file[2][:-1])
            #only need first 6 column (some csv have 10 column)
            new=new.iloc[:,:6]
            new['tem']=tem
            new['mA']=mA
            new['hr']=hr
            dataset.append(new)
            print(new)
          except:
            print('no file')
          
dataset=pd.concat(dataset)

arranged_LI_25C_60mA_12hr.csv
     wavelenght  A  B  C  D  E
0        400.04  0  0  0  0  0
1        400.42  0  0  0  0  0
2        400.80  0  0  0  0  0
3        401.18  0  0  0  0  0
4        401.56  0  0  0  0  0
..          ... .. .. .. .. ..
774      698.09  0  0  0  0  0
775      698.48  0  0  0  0  0
776      698.87  0  0  0  0  0
777      699.26  0  0  0  0  0
778      699.65  0  0  0  0  0

[779 rows x 6 columns]
     wavelenght  A  B  C  D  E  tem  mA  hr
0        400.04  0  0  0  0  0   25  60  12
1        400.42  0  0  0  0  0   25  60  12
2        400.80  0  0  0  0  0   25  60  12
3        401.18  0  0  0  0  0   25  60  12
4        401.56  0  0  0  0  0   25  60  12
..          ... .. .. .. .. ..  ...  ..  ..
774      698.09  0  0  0  0  0   25  60  12
775      698.48  0  0  0  0  0   25  60  12
776      698.87  0  0  0  0  0   25  60  12
777      699.26  0  0  0  0  0   25  60  12
778      699.65  0  0  0  0  0   25  60  12

[779 rows x 9 columns]
arranged_LI_25C_80mA_5hr.csv
     wavelenght  A  B   C   D   E
0        400.04  0  0 NaN NaN NaN
1        400.42  0  0 NaN NaN NaN
2        400.80  0  0 NaN NaN NaN
3        401.18  0  0 NaN NaN NaN
4        401.56  0  0 NaN NaN NaN
..          ... .. ..  ..  ..  ..
775      698.48  0  0 NaN NaN NaN
776      698.87  0  0 NaN NaN NaN
777      699.26  0  0 NaN NaN NaN
778      699.65  0  0 NaN NaN NaN
779         NaN  2  4 NaN NaN NaN

[780 rows x 6 columns]
     wavelenght  A  B   C   D   E  tem  mA  hr
0        400.04  0  0 NaN NaN NaN   25  80   5
1        400.42  0  0 NaN NaN NaN   25  80   5
2        400.80  0  0 NaN NaN NaN   25  80   5
3        401.18  0  0 NaN NaN NaN   25  80   5
4        401.56  0  0 NaN NaN NaN   25  80   5
..          ... .. ..  ..  ..  ..  ...  ..  ..
775      698.48  0  0 NaN NaN NaN   25  80   5
776      698.87  0  0 NaN NaN NaN   25  80   5
777      699.26  0  0 NaN NaN NaN   25  80   5
778      699.65  0  0 NaN NaN NaN   25  80   5
779         NaN  2  4 NaN NaN NaN   25  80   5

[780 rows x 9 columns]
arranged_LI_60C_80mA_0hr.csv
     wavelenght  A  B  C  D  E
0        400.04  0  0  0  0  0
1        400.42  0  0  0  0  0
2        400.80  0  0  0  0  0
3        401.18  0  0  0  0  0
4        401.56  0  0  0  0  0
..          ... .. .. .. .. ..
774      698.09  0  0  0  0  0
775      698.48  0  0  0  0  0
776      698.87  0  0  0  0  0
777      699.26  0  0  0  0  0
778      699.65  0  0  0  0  0

[779 rows x 6 columns]
     wavelenght  A  B  C  D  E  tem  mA  hr
0        400.04  0  0  0  0  0   60  80   0
1        400.42  0  0  0  0  0   60  80   0
2        400.80  0  0  0  0  0   60  80   0
3        401.18  0  0  0  0  0   60  80   0
4        401.56  0  0  0  0  0   60  80   0
..          ... .. .. .. .. ..  ...  ..  ..
774      698.09  0  0  0  0  0   60  80   0
775      698.48  0  0  0  0  0   60  80   0
776      698.87  0  0  0  0  0   60  80   0
777      699.26  0  0  0  0  0   60  80   0
778      699.65  0  0  0  0  0   60  80   0

[779 rows x 9 columns]
arranged_LI_25C_40mA_3hr.csv
     wavelenght  A  B  C  D  E
0        400.04  0  0  0  0  0
1        400.42  0  0  0  0  0
2        400.80  0  0  0  0  0
3        401.18  0  0  0  0  0
4        401.56  0  0  0  0  0
..          ... .. .. .. .. ..
774      698.09  0  0  0  0  0
775      698.48  0  0  0  0  0
776      698.87  0  0  0  0  0
777      699.26  0  0  0  0  0
778      699.65  0  0  0  0  0

[779 rows x 6 columns]
     wavelenght  A  B  C  D  E  tem  mA  hr
0        400.04  0  0  0  0  0   25  40   3
1        400.42  0  0  0  0  0   25  40   3
2        400.80  0  0  0  0  0   25  40   3
3        401.18  0  0  0  0  0   25  40   3
4        401.56  0  0  0  0  0   25  40   3
..          ... .. .. .. .. ..  ...  ..  ..
774      698.09  0  0  0  0  0   25  40   3
775      698.48  0  0  0  0  0   25  40   3
776      698.87  0  0  0  0  0   25  40   3
777      699.26  0  0  0  0  0   25  40   3
778      699.65  0  0  0  0  0   25  40   3

[779 rows x 9 columns]
arranged_LI_60C_60mA_2hr.csv
     wavelenght  A  B  C  D  E
0        400.04  0  0  0  0  0
1        400.42  0  0  0  0  0
2        400.80  0  0  0  0  0
3        401.18  0  0  0  0  0
4        401.56  0  0  0  0  0
..          ... .. .. .. .. ..
774      698.09  0  0  0  0  0
775      698.48  0  0  0  0  0
776      698.87  0  0  0  0  0
777      699.26  0  0  0  0  0
778      699.65  0  0  0  0  0

[779 rows x 6 columns]
     wavelenght  A  B  C  D  E  tem  mA  hr
0        400.04  0  0  0  0  0   60  60   2
1        400.42  0  0  0  0  0   60  60   2
2        400.80  0  0  0  0  0   60  60   2
3        401.18  0  0  0  0  0   60  60   2
4        401.56  0  0  0  0  0   60  60   2
..          ... .. .. .. .. ..  ...  ..  ..
774      698.09  0  0  0  0  0   60  60   2
775      698.48  0  0  0  0  0   60  60   2
776      698.87  0  0  0  0  0   60  60   2
777      699.26  0  0  0  0  0   60  60   2
778      699.65  0  0  0  0  0   60  60   2

[779 rows x 9 columns]
arranged_LI_60C_60mA_5hr.csv
     wavelenght  A  B  C  D  E
0        400.04  0  0  0  0  0
1        400.42  0  0  0  0  0
2        400.80  0  0  0  0  0
3        401.18  0  0  0  0  0
4        401.56  0  0  0  0  0
..          ... .. .. .. .. ..
774      698.09  0  0  0  0  0
775      698.48  0  0  0  0  0
776      698.87  0  0  0  0  0
777      699.26  0  0  0  0  0
778      699.65  0  0  0  0  0

[779 rows x 6 columns]
     wavelenght  A  B  C  D  E  tem  mA  hr
0        400.04  0  0  0  0  0   60  60   5
1        400.42  0  0  0  0  0   60  60   5
2        400.80  0  0  0  0  0   60  60   5
3        401.18  0  0  0  0  0   60  60   5
4        401.56  0  0  0  0  0   60  60   5
..          ... .. .. .. .. ..  ...  ..  ..
774      698.09  0  0  0  0  0   60  60   5
775      698.48  0  0  0  0  0   60  60   5
776      698.87  0  0  0  0  0   60  60   5
777      699.26  0  0  0  0  0   60  60   5
778      699.65  0  0  0  0  0   60  60   5

[779 rows x 9 columns]
arranged_LI_25C_80mA_0hr.csv
     wavelenght  A  B  C  D  E
0        400.04  0  0  0  0  0
1        400.42  0  0  0  0  0
2        400.80  0  0  0  0  0
3        401.18  0  0  0  0  0
4        401.56  0  0  0  0  0
..          ... .. .. .. .. ..
775      698.48  0  0  0  0  0
776      698.87  0  0  0  0  0
777      699.26  0  0  0  0  0
778      699.65  0  0  0  0  0
779         NaN  1  2  3  4  5

[780 rows x 6 columns]
     wavelenght  A  B  C  D  E  tem  mA  hr
0        400.04  0  0  0  0  0   25  80   0
1        400.42  0  0  0  0  0   25  80   0
2        400.80  0  0  0  0  0   25  80   0
3        401.18  0  0  0  0  0   25  80   0
4        401.56  0  0  0  0  0   25  80   0
..          ... .. .. .. .. ..  ...  ..  ..
775      698.48  0  0  0  0  0   25  80   0
776      698.87  0  0  0  0  0   25  80   0
777      699.26  0  0  0  0  0   25  80   0
778      699.65  0  0  0  0  0   25  80   0
779         NaN  1  2  3  4  5   25  80   0

[780 rows x 9 columns]
arranged_LI_60C_60mA_7hr.csv
     wavelenght  A  B  C  D  E
0        400.04  0  0  0  0  0
1        400.42  0  0  0  0  0
2        400.80  0  0  0  0  0
3        401.18  0  0  0  0  0
4        401.56  0  0  0  0  0
..          ... .. .. .. .. ..
774      698.09  0  0  0  0  0
775      698.48  0  0  0  0  0
776      698.87  0  0  0  0  0
777      699.26  0  0  0  0  0
778      699.65  0  0  0  0  0

[779 rows x 6 columns]
     wavelenght  A  B  C  D  E  tem  mA  hr
0        400.04  0  0  0  0  0   60  60   7
1        400.42  0  0  0  0  0   60  60   7
2        400.80  0  0  0  0  0   60  60   7
3        401.18  0  0  0  0  0   60  60   7
4        401.56  0  0  0  0  0   60  60   7
..          ... .. .. .. .. ..  ...  ..  ..
774      698.09  0  0  0  0  0   60  60   7
775      698.48  0  0  0  0  0   60  60   7
776      698.87  0  0  0  0  0   60  60   7
777      699.26  0  0  0  0  0   60  60   7
778      699.65  0  0  0  0  0   60  60   7

[779 rows x 9 columns]
arranged_LI_60C_60mA_12hr.csv
     wavelenght  A  B   C   D   E
0        400.04  0  0 NaN NaN NaN
1        400.42  0  0 NaN NaN NaN
2        400.80  0  0 NaN NaN NaN
3        401.18  0  0 NaN NaN NaN
4        401.56  0  0 NaN NaN NaN
..          ... .. ..  ..  ..  ..
774      698.09  0  0 NaN NaN NaN
775      698.48  0  0 NaN NaN NaN
776      698.87  0  0 NaN NaN NaN
777      699.26  0  0 NaN NaN NaN
778      699.65  0  0 NaN NaN NaN

[779 rows x 6 columns]
     wavelenght  A  B   C   D   E  tem  mA  hr
0        400.04  0  0 NaN NaN NaN   60  60  12
1        400.42  0  0 NaN NaN NaN   60  60  12
2        400.80  0  0 NaN NaN NaN   60  60  12
3        401.18  0  0 NaN NaN NaN   60  60  12
4        401.56  0  0 NaN NaN NaN   60  60  12
..          ... .. ..  ..  ..  ..  ...  ..  ..
774      698.09  0  0 NaN NaN NaN   60  60  12
775      698.48  0  0 NaN NaN NaN   60  60  12
776      698.87  0  0 NaN NaN NaN   60  60  12
777      699.26  0  0 NaN NaN NaN   60  60  12
778      699.65  0  0 NaN NaN NaN   60  60  12

[779 rows x 9 columns]
arranged_LI_25C_60mA_9hr.csv
     wavelenght  A  B  C  D  E
0        400.04  0  0  0  0  0
1        400.42  0  0  0  0  0
2        400.80  0  0  0  0  0
3        401.18  0  0  0  0  0
4        401.56  0  0  0  0  0
..          ... .. .. .. .. ..
774      698.09  0  0  0  0  0
775      698.48  0  0  0  0  0
776      698.87  0  0  0  0  0
777      699.26  0  0  0  0  0
778      699.65  0  0  0  0  0

[779 rows x 6 columns]
     wavelenght  A  B  C  D  E  tem  mA  hr
0        400.04  0  0  0  0  0   25  60   9
1        400.42  0  0  0  0  0   25  60   9
2        400.80  0  0  0  0  0   25  60   9
3        401.18  0  0  0  0  0   25  60   9
4        401.56  0  0  0  0  0   25  60   9
..          ... .. .. .. .. ..  ...  ..  ..
774      698.09  0  0  0  0  0   25  60   9
775      698.48  0  0  0  0  0   25  60   9
776      698.87  0  0  0  0  0   25  60   9
777      699.26  0  0  0  0  0   25  60   9
778      699.65  0  0  0  0  0   25  60   9

[779 rows x 9 columns]
arranged_LI_60C_100mA_0hr.csv
     wavelenght  A  B  C  D  E
0        400.04  0  0  0  0  0
1        400.42  0  0  0  0  0
2        400.80  0  0  0  0  0
3        401.18  0  0  0  0  0
4        401.56  0  0  0  0  0
..          ... .. .. .. .. ..
774      698.09  0  0  0  0  0
775      698.48  0  0  0  0  0
776      698.87  0  0  0  0  0
777      699.26  0  0  0  0  0
778      699.65  0  0  0  0  0

[779 rows x 6 columns]
     wavelenght  A  B  C  D  E  tem   mA  hr
0        400.04  0  0  0  0  0   60  100   0
1        400.42  0  0  0  0  0   60  100   0
2        400.80  0  0  0  0  0   60  100   0
3        401.18  0  0  0  0  0   60  100   0
4        401.56  0  0  0  0  0   60  100   0
..          ... .. .. .. .. ..  ...  ...  ..
774      698.09  0  0  0  0  0   60  100   0
775      698.48  0  0  0  0  0   60  100   0
776      698.87  0  0  0  0  0   60  100   0
777      699.26  0  0  0  0  0   60  100   0
778      699.65  0  0  0  0  0   60  100   0

[779 rows x 9 columns]
arranged_LI_25C_80mA_1hr.csv
     wavelenght  A  B  C  D  E
0        400.04  0  0  0  0  0
1        400.42  0  0  0  0  0
2        400.80  0  0  0  0  0
3        401.18  0  0  0  0  0
4        401.56  0  0  0  0  0
..          ... .. .. .. .. ..
775      698.48  0  0  0  0  0
776      698.87  0  0  0  0  0
777      699.26  0  0  0  0  0
778      699.65  0  0  0  0  0
779         NaN  1  2  3  4  5

[780 rows x 6 columns]
     wavelenght  A  B  C  D  E  tem  mA  hr
0        400.04  0  0  0  0  0   25  80   1
1        400.42  0  0  0  0  0   25  80   1
2        400.80  0  0  0  0  0   25  80   1
3        401.18  0  0  0  0  0   25  80   1
4        401.56  0  0  0  0  0   25  80   1
..          ... .. .. .. .. ..  ...  ..  ..
775      698.48  0  0  0  0  0   25  80   1
776      698.87  0  0  0  0  0   25  80   1
777      699.26  0  0  0  0  0   25  80   1
778      699.65  0  0  0  0  0   25  80   1
779         NaN  1  2  3  4  5   25  80   1

[780 rows x 9 columns]
arranged_LI_25C_60mA_17hr.csv
     wavelenght  A  B  C  D  E
0        400.04  0  0  0  0  0
1        400.42  0  0  0  0  0
2        400.80  0  0  0  0  0
3        401.18  0  0  0  0  0
4        401.56  0  0  0  0  0
..          ... .. .. .. .. ..
774      698.09  0  0  0  0  0
775      698.48  0  0  0  0  0
776      698.87  0  0  0  0  0
777      699.26  0  0  0  0  0
778      699.65  0  0  0  0  0

[779 rows x 6 columns]
     wavelenght  A  B  C  D  E  tem  mA  hr
0        400.04  0  0  0  0  0   25  60  17
1        400.42  0  0  0  0  0   25  60  17
2        400.80  0  0  0  0  0   25  60  17
3        401.18  0  0  0  0  0   25  60  17
4        401.56  0  0  0  0  0   25  60  17
..          ... .. .. .. .. ..  ...  ..  ..
774      698.09  0  0  0  0  0   25  60  17
775      698.48  0  0  0  0  0   25  60  17
776      698.87  0  0  0  0  0   25  60  17
777      699.26  0  0  0  0  0   25  60  17
778      699.65  0  0  0  0  0   25  60  17

[779 rows x 9 columns]
arranged_LI_25C_40mA_2hr.csv
     wavelenght  A  B  C  D  E
0        400.04  0  0  0  0  0
1        400.42  0  0  0  0  0
2        400.80  0  0  0  0  0
3        401.18  0  0  0  0  0
4        401.56  0  0  0  0  0
..          ... .. .. .. .. ..
774      698.09  0  0  0  0  0
775      698.48  0  0  0  0  0
776      698.87  0  0  0  0  0
777      699.26  0  0  0  0  0
778      699.65  0  0  0  0  0

[779 rows x 6 columns]
     wavelenght  A  B  C  D  E  tem  mA  hr
0        400.04  0  0  0  0  0   25  40   2
1        400.42  0  0  0  0  0   25  40   2
2        400.80  0  0  0  0  0   25  40   2
3        401.18  0  0  0  0  0   25  40   2
4        401.56  0  0  0  0  0   25  40   2
..          ... .. .. .. .. ..  ...  ..  ..
774      698.09  0  0  0  0  0   25  40   2
775      698.48  0  0  0  0  0   25  40   2
776      698.87  0  0  0  0  0   25  40   2
777      699.26  0  0  0  0  0   25  40   2
778      699.65  0  0  0  0  0   25  40   2

[779 rows x 9 columns]
arranged_LI_25C_60mA_6hr.csv
     wavelenght  A  B  C  D  E
0        400.04  0  0  0  0  0
1        400.42  0  0  0  0  0
2        400.80  0  0  0  0  0
3        401.18  0  0  0  0  0
4        401.56  0  0  0  0  0
..          ... .. .. .. .. ..
774      698.09  0  0  0  0  0
775      698.48  0  0  0  0  0
776      698.87  0  0  0  0  0
777      699.26  0  0  0  0  0
778      699.65  0  0  0  0  0

[779 rows x 6 columns]
     wavelenght  A  B  C  D  E  tem  mA  hr
0        400.04  0  0  0  0  0   25  60   6
1        400.42  0  0  0  0  0   25  60   6
2        400.80  0  0  0  0  0   25  60   6
3        401.18  0  0  0  0  0   25  60   6
4        401.56  0  0  0  0  0   25  60   6
..          ... .. .. .. .. ..  ...  ..  ..
774      698.09  0  0  0  0  0   25  60   6
775      698.48  0  0  0  0  0   25  60   6
776      698.87  0  0  0  0  0   25  60   6
777      699.26  0  0  0  0  0   25  60   6
778      699.65  0  0  0  0  0   25  60   6

[779 rows x 9 columns]
arranged_LI_25C_40mA_6hr.csv
     wavelenght  A  B  C  D  E
0        400.04  0  0  0  0  0
1        400.42  0  0  0  0  0
2        400.80  0  0  0  0  0
3        401.18  0  0  0  0  0
4        401.56  0  0  0  0  0
..          ... .. .. .. .. ..
774      698.09  0  0  0  0  0
775      698.48  0  0  0  0  0
776      698.87  0  0  0  0  0
777      699.26  0  0  0  0  0
778      699.65  0  0  0  0  0

[779 rows x 6 columns]
     wavelenght  A  B  C  D  E  tem  mA  hr
0        400.04  0  0  0  0  0   25  40   6
1        400.42  0  0  0  0  0   25  40   6
2        400.80  0  0  0  0  0   25  40   6
3        401.18  0  0  0  0  0   25  40   6
4        401.56  0  0  0  0  0   25  40   6
..          ... .. .. .. .. ..  ...  ..  ..
774      698.09  0  0  0  0  0   25  40   6
775      698.48  0  0  0  0  0   25  40   6
776      698.87  0  0  0  0  0   25  40   6
777      699.26  0  0  0  0  0   25  40   6
778      699.65  0  0  0  0  0   25  40   6

[779 rows x 9 columns]
arranged_LI_25C_40mA_7hr.csv
     wavelenght  A  B  C  D  E
0        400.04  0  0  0  0  0
1        400.42  0  0  0  0  0
2        400.80  0  0  0  0  0
3        401.18  0  0  0  0  0
4        401.56  0  0  0  0  0
..          ... .. .. .. .. ..
774      698.09  0  0  0  0  0
775      698.48  0  0  0  0  0
776      698.87  0  0  0  0  0
777      699.26  0  0  0  0  0
778      699.65  0  0  0  0  0

[779 rows x 6 columns]
     wavelenght  A  B  C  D  E  tem  mA  hr
0        400.04  0  0  0  0  0   25  40   7
1        400.42  0  0  0  0  0   25  40   7
2        400.80  0  0  0  0  0   25  40   7
3        401.18  0  0  0  0  0   25  40   7
4        401.56  0  0  0  0  0   25  40   7
..          ... .. .. .. .. ..  ...  ..  ..
774      698.09  0  0  0  0  0   25  40   7
775      698.48  0  0  0  0  0   25  40   7
776      698.87  0  0  0  0  0   25  40   7
777      699.26  0  0  0  0  0   25  40   7
778      699.65  0  0  0  0  0   25  40   7

[779 rows x 9 columns]
arranged_LI_25C_40mA_10hr.csv
     wavelenght  A  B  C  D  E
0        400.04  0  0  0  0  0
1        400.42  0  0  0  0  0
2        400.80  0  0  0  0  0
3        401.18  0  0  0  0  0
4        401.56  0  0  0  0  0
..          ... .. .. .. .. ..
774      698.09  0  0  0  0  0
775      698.48  0  0  0  0  0
776      698.87  0  0  0  0  0
777      699.26  0  0  0  0  0
778      699.65  0  0  0  0  0

[779 rows x 6 columns]
     wavelenght  A  B  C  D  E  tem  mA  hr
0        400.04  0  0  0  0  0   25  40  10
1        400.42  0  0  0  0  0   25  40  10
2        400.80  0  0  0  0  0   25  40  10
3        401.18  0  0  0  0  0   25  40  10
4        401.56  0  0  0  0  0   25  40  10
..          ... .. .. .. .. ..  ...  ..  ..
774      698.09  0  0  0  0  0   25  40  10
775      698.48  0  0  0  0  0   25  40  10
776      698.87  0  0  0  0  0   25  40  10
777      699.26  0  0  0  0  0   25  40  10
778      699.65  0  0  0  0  0   25  40  10

[779 rows x 9 columns]
arranged_LI_25C_100mA_0hr.csv
     wavelenght  A  B  C   D  E
0       400.041  0  0  0   0  0
1       400.422  0  0  0   0  0
2       400.803  0  0  0   0  0
3       401.183  0  0  0   0  0
4       401.564  0  0  0   0  0
..          ... .. .. ..  .. ..
775     698.479  0  0  0   0  0
776     698.868  0  0  0   0  0
777     699.258  0  0  0   0  0
778     699.647  0  0  0   0  0
779         NaN  4  8  9  10  1

[780 rows x 6 columns]
     wavelenght  A  B  C   D  E  tem   mA  hr
0       400.041  0  0  0   0  0   25  100   0
1       400.422  0  0  0   0  0   25  100   0
2       400.803  0  0  0   0  0   25  100   0
3       401.183  0  0  0   0  0   25  100   0
4       401.564  0  0  0   0  0   25  100   0
..          ... .. .. ..  .. ..  ...  ...  ..
775     698.479  0  0  0   0  0   25  100   0
776     698.868  0  0  0   0  0   25  100   0
777     699.258  0  0  0   0  0   25  100   0
778     699.647  0  0  0   0  0   25  100   0
779         NaN  4  8  9  10  1   25  100   0

[780 rows x 9 columns]
arranged_LI_25C_80mA_4hr.csv
     wavelenght  A  B   C   D   E
0        400.04  0  0 NaN NaN NaN
1        400.42  0  0 NaN NaN NaN
2        400.80  0  0 NaN NaN NaN
3        401.18  0  0 NaN NaN NaN
4        401.56  0  0 NaN NaN NaN
..          ... .. ..  ..  ..  ..
775      698.48  0  0 NaN NaN NaN
776      698.87  0  0 NaN NaN NaN
777      699.26  0  0 NaN NaN NaN
778      699.65  0  0 NaN NaN NaN
779         NaN  2  4 NaN NaN NaN

[780 rows x 6 columns]
     wavelenght  A  B   C   D   E  tem  mA  hr
0        400.04  0  0 NaN NaN NaN   25  80   4
1        400.42  0  0 NaN NaN NaN   25  80   4
2        400.80  0  0 NaN NaN NaN   25  80   4
3        401.18  0  0 NaN NaN NaN   25  80   4
4        401.56  0  0 NaN NaN NaN   25  80   4
..          ... .. ..  ..  ..  ..  ...  ..  ..
775      698.48  0  0 NaN NaN NaN   25  80   4
776      698.87  0  0 NaN NaN NaN   25  80   4
777      699.26  0  0 NaN NaN NaN   25  80   4
778      699.65  0  0 NaN NaN NaN   25  80   4
779         NaN  2  4 NaN NaN NaN   25  80   4

[780 rows x 9 columns]
arranged_LI_25C_60mA_11hr.csv
     wavelenght  A  B  C  D  E
0        400.04  0  0  0  0  0
1        400.42  0  0  0  0  0
2        400.80  0  0  0  0  0
3        401.18  0  0  0  0  0



---
## **1. Reshape: normalize+concat**

In [ ]:
df=dataset
df.fillna(0)

     wavelenght  A    B    C    D    E  tem  mA    hr
0        400.04  0  0.0  0.0  0.0  0.0   25  60  12.0
1        400.42  0  0.0  0.0  0.0  0.0   25  60  12.0
2        400.80  0  0.0  0.0  0.0  0.0   25  60  12.0
3        401.18  0  0.0  0.0  0.0  0.0   25  60  12.0
4        401.56  0  0.0  0.0  0.0  0.0   25  60  12.0
..          ... ..  ...  ...  ...  ...  ...  ..   ...
774      698.09  0  0.0  0.0  0.0  0.0   60  60  13.0
775      698.48  0  0.0  0.0  0.0  0.0   60  60  13.0
776      698.87  0  0.0  0.0  0.0  0.0   60  60  13.0
777      699.26  0  0.0  0.0  0.0  0.0   60  60  13.0
778      699.65  0  0.0  0.0  0.0  0.0   60  60  13.0

[49094 rows x 9 columns]

In [ ]:
df_A=df.loc[:,['wavelenght','tem','mA','hr','A']]
df_A['LED']='A'
df_A.columns=['wavelenght','tem','mA','hr','Li','LED']
df_B=df.loc[:,['wavelenght','tem','mA','hr','B']]
df_B['LED']='B'
df_B.columns=['wavelenght','tem','mA','hr','Li','LED']
df_C=df.loc[:,['wavelenght','tem','mA','hr','C']]
df_C['LED']='C'
df_C.columns=['wavelenght','tem','mA','hr','Li','LED']
df_D=df.loc[:,['wavelenght','tem','mA','hr','D']]
df_D['LED']='D'
df_D.columns=['wavelenght','tem','mA','hr','Li','LED']
df_E=df.loc[:,['wavelenght','tem','mA','hr','E']]
df_E['LED']='E'
df_E.columns=['wavelenght','tem','mA','hr','Li','LED']

df=pd.concat([df_A,df_B,df_C,df_D,df_E])
df

     wavelenght  tem  mA    hr   Li LED
0        400.04   25  60  12.0  0.0   A
1        400.42   25  60  12.0  0.0   A
2        400.80   25  60  12.0  0.0   A
3        401.18   25  60  12.0  0.0   A
4        401.56   25  60  12.0  0.0   A
..          ...  ...  ..   ...  ...  ..
774      698.09   60  60  13.0  NaN   E
775      698.48   60  60  13.0  NaN   E
776      698.87   60  60  13.0  NaN   E
777      699.26   60  60  13.0  NaN   E
778      699.65   60  60  13.0  NaN   E

[245470 rows x 6 columns]

In [ ]:
df.to_csv('/content/LI_combined.csv')

In [ ]:
df=df.dropna()
df=df.reset_index().iloc[:,1:]

In [ ]:
indexNames = df[ (df['tem'] == 25)& (df['mA'] == 60)& (df['hr']>=15) ].index
df_dropped=df.drop(indexNames)
df_dropped

        wavelenght  tem  mA    hr   Li LED
0           400.04   25  60  10.0  0.0   A
1           400.42   25  60  10.0  0.0   A
2           400.80   25  60  10.0  0.0   A
3           401.18   25  60  10.0  0.0   A
4           401.56   25  60  10.0  0.0   A
...            ...  ...  ..   ...  ...  ..
216587      698.09   25  40   3.0  0.0   E
216588      698.48   25  40   3.0  0.0   E
216589      698.87   25  40   3.0  0.0   E
216590      699.26   25  40   3.0  0.0   E
216591      699.65   25  40   3.0  0.0   E

[204907 rows x 6 columns]

In [ ]:
indexNames = df_dropped[ (df_dropped['tem'] == 25)& (df_dropped['mA'] == 40)& (df_dropped['hr']>=8) ].index
df_dropped=df_dropped.drop(indexNames)
df_dropped

        wavelenght  tem  mA    hr   Li LED
0           400.04   25  60  10.0  0.0   A
1           400.42   25  60  10.0  0.0   A
2           400.80   25  60  10.0  0.0   A
3           401.18   25  60  10.0  0.0   A
4           401.56   25  60  10.0  0.0   A
...            ...  ...  ..   ...  ...  ..
216587      698.09   25  40   3.0  0.0   E
216588      698.48   25  40   3.0  0.0   E
216589      698.87   25  40   3.0  0.0   E
216590      699.26   25  40   3.0  0.0   E
216591      699.65   25  40   3.0  0.0   E

[193222 rows x 6 columns]

In [ ]:
df_dropped.to_csv('/content/LI_combined2.csv')

In [ ]:
for name,group in df_dropped.groupby(['tem','mA','hr']):
  print(name)
  print(group)

In [ ]:
import numpy as np
df_dropped.groupby(['tem','mA','hr'])['Li'].agg(np.max)

tem  mA   hr
25   40   0.0     2556.0
          1.0     3952.0
          2.0     3733.0
          3.0     3855.0
          4.0     3912.0
          5.0     3815.0
          6.0     3697.0
          7.0     3580.0
     60   0.0     3282.0
          2.0     3091.0
          3.0     2756.0
          4.0     2936.0
          5.0     2919.0
          6.0     2615.0
          7.0     2721.0
          8.0     2723.0
          9.0     2648.0
          10.0    2544.0
          11.0    2472.0
          12.0    2265.0
          13.0    2096.0
          14.0    1801.0
     80   0.0     3932.0
          1.0     2640.0
          2.0     2286.0
          3.0     1363.0
          4.0      920.0
          5.0      735.0
     100  0.0     4095.0
          1.0     3205.0
          2.0     3095.0
          3.0     2798.0
          4.0     3103.0
          5.0     2467.0
          6.0     2104.0
60   60   0.0     2486.0
          1.0     3161.0
          2.0     2871.0
          3.0     2469.0
          4.0     2170.0
          5.0     2094.0
          6.0     2190.0
          7.0     1843.0
          8.0     1248.0
          9.0     1136.0
          10.0     410.0
          11.0    1073.0
          12.0    1152.0
          13.0     984.0
          13.5     550.0
     80   0.0     3062.0
          0.5     1448.0
          1.0      922.0
          1.5      844.0
          2.0      708.0
          3.0      215.0
     100  0.0     3668.0
Name: Li, dtype: float64



---
## **2. Add Feature: Mean of A-E**

In [ ]:
df=dataset
df=df.drop(index=779).fillna(0)
df['mean']= df.loc[:,['A','B','C','D','E']].mean(axis=1)
df[df['mean']!=0]

     wavelenght  A      B    C     D    E  tem  mA    hr  mean
104      439.69  0    9.0  0.0   0.0  0.0   25  60  12.0   1.8
105      440.07  0  100.0  0.0   0.0  0.0   25  60  12.0  20.0
106      440.45  0  169.0  0.0   0.0  0.0   25  60  12.0  33.8
107      440.84  0  262.0  0.0   0.0  0.0   25  60  12.0  52.4
108      441.22  0  309.0  0.0  46.0  0.0   25  60  12.0  71.0
..          ... ..    ...  ...   ...  ...  ...  ..   ...   ...
567      617.72  0   37.0  0.0   0.0  0.0   60  60  13.0   7.4
568      618.11  0    8.0  0.0   0.0  0.0   60  60  13.0   1.6
569      618.50  0   16.0  0.0   0.0  0.0   60  60  13.0   3.2
570      618.88  0   13.0  0.0   0.0  0.0   60  60  13.0   2.6
571      619.27  0   10.0  0.0   0.0  0.0   60  60  13.0   2.0

[21700 rows x 10 columns]

In [ ]:
df_A=df.loc[:,['wavelenght','tem','mA','hr','A']]
df_A['LED']='A'
df_A.columns=['wavelenght','tem','mA','hr','Li','LED']
df_B=df.loc[:,['wavelenght','tem','mA','hr','B']]
df_B['LED']='B'
df_B.columns=['wavelenght','tem','mA','hr','Li','LED']
df_C=df.loc[:,['wavelenght','tem','mA','hr','C']]
df_C['LED']='C'
df_C.columns=['wavelenght','tem','mA','hr','Li','LED']
df_D=df.loc[:,['wavelenght','tem','mA','hr','D']]
df_D['LED']='D'
df_D.columns=['wavelenght','tem','mA','hr','Li','LED']
df_E=df.loc[:,['wavelenght','tem','mA','hr','E']]
df_E['LED']='E'
df_E.columns=['wavelenght','tem','mA','hr','Li','LED']
df_M=df.loc[:,['wavelenght','tem','mA','hr','mean']]
df_M['LED']='Mean'
df_M.columns=['wavelenght','tem','mA','hr','Li','LED']

df=pd.concat([df_A,df_B,df_C,df_D,df_E,df_M])
df

     wavelenght  tem  mA    hr   Li   LED
0        400.04   25  60  12.0  0.0     A
1        400.42   25  60  12.0  0.0     A
2        400.80   25  60  12.0  0.0     A
3        401.18   25  60  12.0  0.0     A
4        401.56   25  60  12.0  0.0     A
..          ...  ...  ..   ...  ...   ...
774      698.09   60  60  13.0  0.0  Mean
775      698.48   60  60  13.0  0.0  Mean
776      698.87   60  60  13.0  0.0  Mean
777      699.26   60  60  13.0  0.0  Mean
778      699.65   60  60  13.0  0.0  Mean

[294462 rows x 6 columns]

In [ ]:
df.to_csv('/content/LI_combined4.csv')